name: lobolabs_ebalance_flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '3.1.1'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.20.0-nullsafety.3
  shared_preferences: ^2.1.1
  http: ^0.13.6
  flutter_bloc: 8.1.3
  bloc: 8.1.2
  equatable: ^2.0.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
#  fonts:
#    - family: poppings
#      fonts:
#        - asset: fonts/poppings.ttf
#        - asset: fonts/poppings-bold.ttf
#          style: italic
  uses-material-design: true

assets:
  - assets/company.svg
  - assets/customer.svg
  - assets/provider.svg
  - assets/receiver.svg
  - assets/user.svg
  - assets/signout.svg


